import { defineSchema, defineTable } from 'convex/server'
import { v } from 'convex/values'

const status = v.union(v.literal('candidate'), v.literal('active'), v.literal('ending_soon'), v.literal('needs_recheck'), v.literal('expired'), v.literal('dead'), v.literal('archived'), v.literal('replaced'))
const sourceStatus = v.union(v.literal('active'), v.literal('deleted'), v.literal('unreachable'), v.literal('login_required'))
const reactionType = v.union(v.literal('claimed'), v.literal('works'), v.literal('expired'), v.literal('needs_card'), v.literal('region_issue'), v.literal('not_free'))

export default defineSchema({
  providers: defineTable({ name: v.string(), slug: v.string(), logoUrl: v.optional(v.string()), createdAt: v.number() }).index('by_slug', ['slug']),
  resources: defineTable({ slug: v.string(), providerId: v.id('providers'), title: v.string(), description: v.string(), category: v.string(), resourceType: v.string(), valueText: v.optional(v.string()), originalClaimUrl: v.optional(v.string()), resolvedClaimUrl: v.optional(v.string()), requiresCard: v.boolean(), requiresApplication: v.boolean(), availabilityType: v.optional(v.string()), status, startsAt: v.optional(v.number()), expiresAt: v.optional(v.number()), firstSeenAt: v.number(), lastSeenAt: v.number(), lastVerifiedAt: v.optional(v.number()), communityConfirmedAt: v.optional(v.number()), consecutiveFailures: v.number(), eventName: v.optional(v.string()), createdAt: v.number(), updatedAt: v.number(), archivedAt: v.optional(v.number()) }).index('by_slug', ['slug']).index('by_status', ['status']).index('by_provider', ['providerId']),
  resourceSources: defineTable({ resourceId: v.id('resources'), sourceType: v.string(), sourceUrl: v.string(), authorName: v.optional(v.string()), authorHandle: v.optional(v.string()), isPrimary: v.boolean(), status: sourceStatus, firstSeenAt: v.number(), lastCheckedAt: v.number(), createdAt: v.number() }).index('by_resource', ['resourceId']),
  resourceReactions: defineTable({ resourceId: v.id('resources'), reactionType, anonymousId: v.string(), country: v.optional(v.string()), createdAt: v.number(), updatedAt: v.number() }).index('by_resource', ['resourceId']).index('by_visitor_reaction', ['resourceId', 'anonymousId', 'reactionType']),
  resourceChecks: defineTable({ resourceId: v.id('resources'), checkedAt: v.number(), httpStatus: v.optional(v.number()), finalUrl: v.optional(v.string()), offerDetected: v.boolean(), result: v.string(), changeSummary: v.optional(v.string()), error: v.optional(v.string()) }).index('by_resource', ['resourceId']),
  resourceVersions: defineTable({ resourceId: v.id('resources'), valueText: v.optional(v.string()), eligibility: v.array(v.string()), expiresAt: v.optional(v.number()), claimUrl: v.optional(v.string()), requirements: v.array(v.string()), regions: v.array(v.string()), createdAt: v.number() }).index('by_resource', ['resourceId']),
  resourceCandidates: defineTable({ sourceUrl: v.string(), provider: v.string(), title: v.string(), description: v.string(), category: v.string(), resourceType: v.string(), valueText: v.optional(v.string()), eligibility: v.array(v.string()), requirements: v.array(v.string()), regions: v.array(v.string()), requiresCard: v.boolean(), requiresApplication: v.boolean(), claimUrl: v.optional(v.string()), evidence: v.optional(v.string()), status: v.union(v.literal('pending'), v.literal('approved'), v.literal('rejected')), createdAt: v.number(), reviewedAt: v.optional(v.number()) }).index('by_status', ['status']),
  discoveryQueries: defineTable({ query: v.string(), enabled: v.boolean(), cadenceHours: v.number(), lastRunAt: v.optional(v.number()), createdAt: v.number() }).index('by_enabled', ['enabled']),
  submissions: defineTable({ url: v.string(), anonymousId: v.string(), status: v.union(v.literal('queued'), v.literal('processing'), v.literal('candidate'), v.literal('rejected')), candidateId: v.optional(v.id('resourceCandidates')), createdAt: v.number() }).index('by_status', ['status']),
})
